### ISSUE TITLE
List third party libraries for use with GOV.UK One Login

### ISSUE THREAD

**Issue by huwd** [govuk-one-login/tech-docs#156]
Some teams have started to open source the code they use to interact with us.
I wonder if it's useful to review which of those we endorse and then list them.

Discovering something like this could save an RP a lot of time?

## Current ones we're aware of:

| maintainer  | repository  |  license  |  framework  |  language  |
|---|---|---|---|---|
| [DFE-Digital](https://github.com/DFE-Digital) | [one-login-aspnetcore](https://github.com/DFE-Digital/one-login-aspnetcore)  |  [MIT](https://github.com/DFE-Digital/one-login-aspnetcore/blob/main/LICENSE) | [ASP.NET](http://asp.net/)   | C#   |
| [SkillsFundingAgency](https://github.com/SkillsFundingAgency)   | [das-shared-packages](https://github.com/SkillsFundingAgency/das-shared-packages/tree/master/SFA.DAS.GovUK.Auth)    | [MIT](https://github.com/SkillsFundingAgency/das-shared-packages/blob/master/LICENSE) |   | C#   |
|[GDS](https://github.com/govuk-one-login) |[relying-party-stub](https://github.com/govuk-one-login/relying-party-stub) | [MIT](https://github.com/govuk-one-login/relying-party-stub/blob/main/LICENCE) | [com.nimbusds/oauth2-oidc-sdk](https://mvnrepository.com/artifact/com.nimbusds/oauth2-oidc-sdk) |  Java |

**Comment by mrwilson** [comment]
SFA have another ASP.NET library https://github.com/SkillsFundingAgency/das-shared-packages/tree/master/SFA.DAS.GovUK.Auth

**Comment by huwd** [comment]
Yeah let's list everything we know of.
Tech writers and our RP experts can then decide what's relevant for our external docs

**Comment by pauldougan** [comment]
@huwd i have a list of things that i have been curating, we should talk

**Comment by sabrinaharris** [comment]
Yes, just to add that Elena has been looking at this with @pauldougan and @philf999 I believe. We know the standard OIDC list of libraries we linked to previously was unhelpful because several of the options did not work, so it'd be great to have specific examples that we have confidence in.

**Comment by huwd** [comment]
Cool, I'll catch up with Paul tomorrow, find the best way to feed this in.

**Comment by pauldougan** [comment]
we had a chat with an RP today (using node) who explicitly asked for nodejs library recommendations for:
- handling the JWTs
- oidc

**Comment by pauldougan** [comment]
Ok this is the subject of [AP-121](https://govukverify.atlassian.net/browse/AP-121) so I'm goiing to link the two together and close this down
