### ISSUE TITLE
Upgrade to Ruby 3.3.1 to fix apple issues

### ISSUE THREAD

**Issue by huwd** [govuk-one-login/tech-docs#166]
Not yet released but noting this [PR](https://github.com/govuk-one-login/authentication-tech-docs/pull/165).

Currently 3.3.0 has build issues on Apples new Mac with the fancy processors.
Ruby are working on a fix, should be 3.3.1 soon.

Don't upgrade back to 3.3.0 until we've confirmed that's fixed and tested with the tech writers.

**Comment by pauldougan** [comment]
@huwd looks like 3.3.1 was shipped on April 24 so this story is no longer blocked https://www.ruby-lang.org/en/news/2024/04/23/ruby-3-3-1-released/
