### ISSUE TITLE
hmcts.net account access to Slack

### ISSUE THREAD

**Issue by hmcts-jmoore** [govuk-one-login/tech-docs#221]
I am an hmcts.net user doing some initial investigations and prototyping.  I can get access to the integration environment, and join the mailing list, but I can't get access to Slack, and I have some questions I'd like to as there.

(When I try to join the Slack channel, I get an email with the subject "No account found", which says "It looks like there isn’t an account on UK Government Digital tied to this email address.")

**Comment by pauldougan** [comment]
@hmcts-jmoore You can use the https://www.sign-in.service.gov.uk/contact-us support form to send in your questions about the GOV.UK One Login integration environment if you cannot access cross government slack.

**Comment by hmcts-jmoore** [comment]
@pauldougan - thanks.  There are a couple of different support links.  I tried the wrong one first :-)
